apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.name}}-secret
  namespace: {{.Values.namespace}}
stringData:
  PORT : "5000"
  JWT_SECRET: "secret"
  MONGO_CONNECTION_URI: "mongodb://root:password@banner-mongodb-0.banner-mongodb-headless.{{.Values.namespace}},banner-mongodb-1.banner-mongodb-headless.{{.Values.namespace}},banner-mongodb-2.banner-mongodb-headless.{{.Values.namespace}}:27017/admin"