namespace: default
name: banner
deployment:
  client:
    replicas: 1
    image:
      repository: banner-front
      name: banner-client
      tag: 0.1.0
    base_url: http://localhost/banner/api
  server:
    replicas: 1
    image:
      repository: isaschar/banner-back
      name: banner-server
      tag: 1.0.0
ingress:
  client:
    path: /banner(/|$)(.*)
    pathType: ImplementationSpecific
  server:
    path: /banner/api(/|$)(.*)
    pathType: ImplementationSpecific
mongodb:
  global:
    namespaceOverride: default
  fullnameOverride: banner-mongodb
  architecture: replicaset
  auth:
    enabled: true
    rootUser: root
    rootPassword: password
  replicaCount: 3
  persistence:
    size: 1Gi
  arbiter:
    enabled: false
  
